import { Geist, Geist_Mono } from "next/font/google";
import { localFont } from "@next/font/local";
import "./globals.css";
import Script from "next/script";

// const sfPro = localFont({
//   // Moved declaration to the top
//   src: [
//     {
//       path: "../public/fonts/SFPRODISPLAYREGULAR.otf",
//       weight: "400",
//       style: "regular",
//     },
//     {
//       path: "../public/fonts/SFPRODISPLAYMEDIUM.otf",
//       weight: "500",
//       style: "medium",
//     },
//     {
//       path: "../public/fonts/SFPRODISPLAYBOLD.otf",
//       weight: "700",
//       style: "bold",
//     },
//   ],
//   variable: "--font-sf-pro",
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Space O technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        <Script
          src="https://unpkg.com/@tailwindcss/browser@4"
          strategy="lazyOnload"
        ></Script>
      </body>
    </html>
  );
}
